baseURL = "https://diegoneves.eti.br"
languageCode = "en-us"
title = "My New Site"
theme = "hyde-x"
copyright = "&copy; 2012. Some rights reserved."
canonifyurls = true
paginate = 10
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[author]
    name = "Diego Neves"
    homepage = "https://diegoneves.eti.br"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title"

[taxonomies]
  tag = "tags"
  topic = "categories"

[params]
  # Shown in the home page
  home = "Home"
  truncate = true
  defaultDescription = "Deploying a better new world"
  hideReadingTime = true
  theme = "theme-base-07"
  googleAnalytics = "UA-167610562-1"
  gravatarHash = "4ccb418dfbd778da7d91e1d619247917"
  github = "https://github.com/diegoaceneves"
  bitbucket = ""
  stackOverflow = ""
  linkedin = "https://www.linkedin.com/in/diegoaceneves/"
  instagram = "https://instagram.com/diegoaceneves/"
  facebook = "https://fb.me/diegoaceneves"
  twitter = "https://twitter.com/diegoaceneves"
  youtube = ""
  rss = true

  [menu]
    # Shown in the side menu.
    [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 1
      identifier = "home"
      url = "/"
    [[menu.main]]
      name = "Posts"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 2
      identifier = "posts"
      url = "/posts"
    [[menu.main]]
      name = "About"
      pre = "<i class='fa fa-user fa-fw'></i>"
      weight = 3
      identifier = "about"
      url = "/about/"
    [[menu.main]]
      name = "Curriculo"
      pre = "<i class='fa fa-list fa-fw'></i>"
      weight = 4
      identifier = "curriculo"
      url = "/curriculo"